replicaCount: 1

nodeSelector: production

namespace: production

metadata:
  deployment: service-C-production
  service: service-C-services-production
  hpa: hpa-service-C-production

image:
  repository: sehatq/service-C
  tag: production
  pullPolicy: Always

port: 
  type: ClusterIP
  containerport: 3000
  serviceport: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    # cpu:
    #   targetAverageUtilization: 60
    memory:
      targetAverageUtilization: 70
