replicaCount: 1

nodeSelector: production

namespace: production

metadata:
  deployment: service-B-production
  service: service-B-services-production
  ingress: service-B-ingress
  hpa: hpa-service-B-production

image:
  repository: sehatq/service-B
  tag: production
  pullPolicy: Always

port: 
  type: ClusterIP
  containerport: 3000
  serviceport: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  labels: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: sehatq-com-tls
      hosts:
        - sehatq.com
  rules:
    - host: sehatq.com
      http:
        paths:
          - path: /shop
            backend:
              serviceName: service-B-services-production
              servicePort: 3000
  
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    # cpu:
    #   targetAverageUtilization: 60
    memory:
      targetAverageUtilization: 70
