apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.service }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    name: {{ .Values.metadata.service }}
  type: {{ .Values.port.type }}
  ports:
    - port: {{ .Values.port.serviceport }}
      targetPort: {{ .Values.port.containerport }}